### ISSUE TITLE
How inject array of dict into key value ? 

### ISSUE THREAD

**Issue by reyman** [buchen/fix-info-plist-maven-plugin#1]
Hi,

I need to inject a dict into my plist, is it possible with your plugin ? 

```
    <key>CFBundleDocumentTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeExtensions</key>
            <array>
                <string>gaml</string>
            </array>
            <key>CFBundleTypeIconFile</key>
            <string>Model.icns</string>
            <key>CFBundleTypeName</key>
            <string>Gama Model</string>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleTypeOSTypes</key>
            <array>
                <string>TEXT</string>
            </array>
        </dict>
    </array>
```

**Comment by buchen** [comment]
Currently not.

Only if there is already an existing key of type array, one can set a comma-separate list of values:

``` xml
<property>
    <name>CFBundleLocalizations</name>
    <value>en,de</value>
</property>
```

**Comment by reyman** [comment]
Ok @buchen !

And do you think is it possible to inject into CFBundleDocumentTypes <value> using some injection of text, like CDATA ?

**Comment by buchen** [comment]
With current implementation I do not think so. But it should be fairly simple to implement it. As you [can see here](https://github.com/buchen/fix-info-plist-maven-plugin/blob/master/src/main/java/name/abuchen/mvn/FixInfoPlistMojo.java#L84), the NSArray is detected based on the current value, why not change that to detection based on the given value, say `[en,de]` as array? If it helps, I could to that improvement tomorrow.

**Comment by reyman** [comment]
Great @buchen , this key `CFBundleDocumentTypes` is relatively common for macosx definition in eclipse, so if you implement this, it can be usefull for others too :) :+1:

**Comment by buchen** [comment]
With version 1.1, this

``` xml
<property>
    <name>CFBundleTypeExtensions</name>
    <value>[gaml]</value>
</property>
<property>
    <name>CFBundleTypeOSTypes</name>
    <value>[TEXT]</value>
</property>
```

creates this

``` xml
<key>CFBundleTypeOSTypes</key>
<array>
    <string>TEXT</string>
</array>
<key>CFBundleTypeExtensions</key>
<array>
    <string>gaml</string>
</array>
```
