### ISSUE TITLE
Binary MD5 hash in "download.checksum.md5" property in artifacts.xml is not updated

### ISSUE THREAD

**Issue by vikonomou** [buchen/fix-info-plist-maven-plugin#4]
The `fixZippedBinaryArchiveInRepository(Path infoPlist)` method in the `FixInfoPlistMojo` class does not update the MD5 hash of the binary in the "download.checksum.md5" property because of a spelling error in the code line `messageFormat = "<property name=''ownload.checksum.md5'' value=''{0}''/>"; //$NON-NLS-1$`.
So far, only the hashes of the properties "download.md5" and "download.checksum.sha-256" are being updated correctly.

Could you provide a new release with a fix for this bug please? That would be great!

**Comment by buchen** [comment]
I'll fix it, of course. Need a couple days until I have the time to publish to Maven Central.

**Comment by buchen** [comment]
published version 1.6 to Maven Central
