### ISSUE TITLE
Patch two products

### ISSUE THREAD

**Issue by 20100** [buchen/fix-info-plist-maven-plugin#6]
Thanks for this plugin very useful. 
Is there a solution to patch two product in the same time ?
Thanks

**Comment by buchen** [comment]
You can configure the plugin multiple times if you have multiple products.

See this example (please not that the configuration section is identical - and therefore a little bit further up in the pom.xml).

https://github.com/buchen/portfolio/blob/master/portfolio-product/pom.xml#L164-L189

**Comment by 20100** [comment]
Thanks, it works good.
